version: '2'
services:
  ## 数据缓存服务
  redis:
    image: redis:6.2.6
    command: redis-server /etc/redis/redis.conf --appendonly yes
    container_name: sdf-redis
    restart: always
    volumes:
      - './redis/conf/redis.conf:/etc/redis/redis.conf'
      - './redis/data:/data'

  ## 前端网关
  sdf-fgw:
    image: iotportal/sdf-gw:latest
    links:
      - redis
    container_name: sdf-fgw
    environment:
      DEVELOPER_CODE: ${DEVELOPER_CODE}
      DEVELOPER_KEY: ${DEVELOPER_KEY}
      HIGHWAY_URL: ${OPEN_API}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      CUSTOM_API_URL: ${CUSTOM_API_URL}
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - redis
    ports:
      - 3000:3000
    restart: always
